import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '首页',
    },
    {
      type: 'category',
      label: 'Week 1: 内核解剖与构建体系',
      collapsed: false,
      items: [
        'part1/day01-02-setup',
        'part1/day03-04-kconfig',
        'part1/day05-06-data-structs',
        'part1/day07-qemu',
      ],
    },
  ],

  referenceSidebar: [
    {
      type: 'category',
      label: '参考文档',
      items: [
        'booklist',
        'qemu-reference',
      ],
    },
  ],

  notesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'notes',
    },
  ],
};

export default sidebars;
