import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '首页',
    },
    {
      type: 'autogenerated',
      dirName: 'tutorials',
    },
  ],

  referenceSidebar: [
    {
      type: 'category',
      label: '参考文档',
      items: [
        'booklist',
        'qemu-reference',
      ],
    },
  ],

  notesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'notes',
    },
  ],
};

export default sidebars;
